export interface Author {
    id: string;         // Autogenerated ID (e.g., "A0001")
    name: string;       // Author name
    bio: string;        // Author biography
    email: string;      // Contact email
  }
  