export interface Course {
    id: string;         // Autogenerated ID (e.g., "C0001")
    name: string;       // Course name
    description: string; // Course description
    duration: number;   // Duration in hours
    authorId: string;   // Associated author ID
  }
  