export interface Review {
    id: string;         // Autogenerated ID (e.g., "RV0001")
    courseId: string;   // Associated course ID
    learnerId: string;  // Associated learner ID
    rating: number;     // Rating (e.g., 1–5)
    comment: string;    // Review comment
  }
  